# Generated by Django 3.2.15 on 2022-08-25 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220819_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='dob',
        ),
    ]
